# Generated by Django 4.2.6 on 2023-11-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseapp', '0002_product_orders_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qty',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
