# Generated by Django 4.2.6 on 2023-11-24 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseapp', '0003_product_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='image',
            new_name='photo',
        ),
    ]
