# Generated by Django 4.2.6 on 2023-11-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseapp', '0004_rename_image_client_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Mobile', models.IntegerField(null=True)),
                ('Address', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
