# Generated by Django 4.2.6 on 2023-11-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseapp', '0005_addressform'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressform',
            name='Delivery_method',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
