# Generated by Django 4.2.6 on 2023-11-25 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseapp', '0007_delivery1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='age',
        ),
        migrations.RemoveField(
            model_name='delivery1',
            name='age',
        ),
    ]
