# Generated by Django 4.2.6 on 2023-11-25 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseapp', '0008_remove_delivery_age_remove_delivery1_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='address',
        ),
        migrations.RemoveField(
            model_name='delivery1',
            name='address',
        ),
    ]
