# Generated by Django 4.2.6 on 2023-11-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseapp', '0009_remove_delivery_address_remove_delivery1_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery1',
            name='user_type',
            field=models.CharField(default=2, max_length=10),
        ),
    ]
