# Generated by Django 4.2.6 on 2023-11-25 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseapp', '0010_delivery1_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery1',
            name='email',
        ),
        migrations.RemoveField(
            model_name='delivery1',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='delivery1',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='delivery1',
            name='user_type',
        ),
        migrations.RemoveField(
            model_name='delivery1',
            name='username',
        ),
        migrations.AddField(
            model_name='delivery1',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
