# Generated by Django 4.2.6 on 2023-11-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseapp', '0012_remove_delivery1_user_delivery1_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='photo',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
