# Generated by Django 4.2.6 on 2023-11-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseapp', '0014_alter_client_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(default=3, max_length=10)),
                ('age', models.IntegerField(null=True)),
                ('number', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('photo', models.FileField(null=True, upload_to='image/')),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('username', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
    ]
