# Generated by Django 4.2.6 on 2023-11-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseapp', '0015_client1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client1',
        ),
        migrations.AddField(
            model_name='delivery1',
            name='client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='delivery1',
            name='delivery',
            field=models.BooleanField(default=False),
        ),
    ]
