# Generated by Django 4.2.6 on 2023-11-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseapp', '0016_delete_client1_delivery1_client_delivery1_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery1',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
